In [58]:
import pandas as pd

# Sample DataFrame
data = {'A': [1, 3, 2, 5, 4],
        'C': [5,4,3,2,1],
        'B': ["A","A","A","B","B"]}
df = pd.DataFrame(data)

# Define a rolling window with size 3 (current row + next 2 rows)
rolling_window = df['A'].rolling(window=3)

In [17]:
df

A  C  B
0  1  5  A
1  3  4  A
2  2  3  A
3  5  2  B
4  4  1  B

In [31]:
df.groupby("B", group_keys=False).apply(lambda x:x.sort_values(["A","C"]).head(2))

A  C  B
0  1  5  A
2  2  3  A
4  4  1  B
3  5  2  B

In [25]:
df.groupby("B", group_keys=False)["C"].rank("dense")

0    3.0
1    2.0
2    1.0
3    2.0
4    1.0
Name: C, dtype: float64

In [30]:
df.groupby("B", group_keys=False).transform(lambda x:x**2)

A   C
0   1  25
1   9  16
2   4   9
3  25   4
4  16   1

In [43]:
df.groupby("B", group_keys=False).rolling(2).min()

A    C
B            
A 0  NaN  NaN
  1  1.0  4.0
  2  2.0  3.0
B 3  NaN  NaN
  4  4.0  1.0

In [33]:
df.groupby("B").describe()

A                                               C                      \
  count mean       std  min   25%  50%   75%  max count mean       std  min   
B                                                                             
A   3.0  2.0  1.000000  1.0  1.50  2.0  2.50  3.0   3.0  4.0  1.000000  3.0   
B   2.0  4.5  0.707107  4.0  4.25  4.5  4.75  5.0   2.0  1.5  0.707107  1.0   

                         
    25%  50%   75%  max  
B                        
A  3.50  4.0  4.50  5.0  
B  1.25  1.5  1.75  2.0

In [34]:
df.groupby("B").head(2)

A  C  B
0  1  5  A
1  3  4  A
3  5  2  B
4  4  1  B

In [35]:
df.groupby("B").first()

A  C
B      
A  1  5
B  5  2

In [47]:
df["A_lead"] = df.groupby("B", group_keys=False).shift(1)["A"]

In [48]:
df["A_lag"] = df.groupby("B", group_keys=False).shift(-1)["A"]

In [49]:
df

A  C  B  A_lead  A_lag
0  1  5  A     NaN    3.0
1  3  4  A     1.0    2.0
2  2  3  A     3.0    NaN
3  5  2  B     NaN    4.0
4  4  1  B     5.0    NaN

In [64]:
df.groupby("B", group_keys=False).rolling(2).sum().shift(-1)

A    C
B            
A 0  4.0  9.0
  1  5.0  7.0
  2  NaN  NaN
B 3  9.0  3.0
  4  NaN  NaN

In [61]:
df

A  C  B
0  1  5  A
1  3  4  A
2  2  3  A
3  5  2  B
4  4  1  B

In [1]:
import numpy as np

np.bincount([1,1,2,2,3,3,3])

array([0, 2, 2, 3])

In [4]:
from collections import Counter

dict(Counter([1,2,2,3,4]))

{1: 1, 2: 2, 3: 1, 4: 1}

In [6]:
sample = np.array([[1,2],[3,4]])
sample

array([[1, 2],
       [3, 4]])

In [7]:
sample.mean(axis=0)

array([2., 3.])

In [8]:
sample.mean(axis=1)

array([1.5, 3.5])

In [9]:
sample.mean()

2.5

In [10]:
sample = np.array([1,3])

In [11]:
sample.reshape(sample.shape[0],1)

array([[1],
       [3]])

In [12]:
np.expand_dims(sample, axis=1)

array([[1],
       [3]])